### ISSUE TITLE
[BUG] thread 'tokio-runtime-worker' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)'

### ISSUE THREAD

**Issue by Sad-theFaceless** [epi052/feroxbuster#689]
Hello,

In the middle of scanning a machine (Hack The Box "Awkward" reseted machine), feroxbuster stopped while displaying this error:

```
$ feroxbuster --no-state -egBE -w /usr/share/seclists/Discovery/Web-Content/common.txt -x php,sh,txt,cgi,html,js,css,py,log,conf,json,ini,pdf,bak,old,zip,tar,gz,tgz,rar,docx,rtf,xlsx,pptx,asp,jsp -C 403,404 -u 'http://hat-valley.htb/'

 ___  ___  __   __     __      __         __   ___
|__  |__  |__) |__) | /  `    /  \ \_/ | |  \ |__
|    |___ |  \ |  \ | \__,    \__/ / \ | |__/ |___
by Ben "epi" Risher 🤓                 ver: 2.7.1
───────────────────────────┬──────────────────────
 🎯  Target Url            │ http://hat-valley.htb/
 🚀  Threads               │ 50
 📖  Wordlist              │ /usr/share/seclists/Discovery/Web-Content/common.txt
 💢  Status Code Filters   │ [403, 404]
 💥  Timeout (secs)        │ 7
 🦡  User-Agent            │ feroxbuster/2.7.1
 💉  Config File           │ /etc/feroxbuster/ferox-config.toml
 🔎  Extract Links         │ true
 💲  Extensions            │ [php, sh, txt, cgi, html, js, css, py, log, conf, json, ini, pdf, bak, old, zip, tar, gz, tgz, rar, docx, rtf, xlsx, pptx, asp, jsp]
 💰  Collect Extensions    │ true
 💸  Ignored Extensions    │ [Images, Movies, Audio, etc...]
 🏦  Collect Backups       │ true
 🤑  Collect Words         │ true
 🏁  HTTP methods          │ [GET]
 🔃  Recursion Depth       │ 4
───────────────────────────┴──────────────────────
 🏁  Press [ENTER] to use the Scan Management Menu™
──────────────────────────────────────────────────
WLD      GET       54l      163w     2881c Got 200 for http://hat-valley.htb/f9ca3e24ff5f4bcba810a75032bb2fcb (url length: 32)
WLD      GET         -         -         - Wildcard response is static; auto-filtering 2881 responses; toggle this behavior by using --dont-filter
301      GET       10l       16w      173c http://hat-valley.htb/css => /css/
200      GET        1l       35w     4286c http://hat-valley.htb/favicon.ico
301      GET       10l       16w      171c http://hat-valley.htb/js => /js/
[#######>------------] - 10m   497584/1404538 19m     found:4       errors:2      
[############>-------] - 10m    80354/127278  127/s   http://hat-valley.htb/ 
[############>-------] - 10m    80163/127278  127/s   http://hat-valley.htb/.git/logs/ 
[########>-----------] - 9m     53325/127278  93/s    http://hat-valley.htb/cgi-bin/ 
[########>-----------] - 9m     52920/127278  93/s    http://hat-valley.htb/.git/logs/cgi-bin/ 
[########>-----------] - 9m     52866/127278  93/s    http://hat-valley.htb/cgi-bin/.git/logs/ 
[#######>------------] - 8m     45495/127278  87/s    http://hat-valley.htb/css 
[#######>------------] - 8m     45009/127278  87/s    http://hat-valley.htb/css/.git/logs/ 
[####>---------------] - 5m     25704/127278  74/s    http://hat-valley.htb/cgi-bin/cgi-bin/ 
[##>-----------------] - 4m     18225/127278  65/s    http://hat-valley.htb/css/cgi-bin/ 
[##>-----------------] - 4m     17550/127278  66/s    http://hat-valley.htb/js 
[##>-----------------] - 4m     17550/127278  66/s    http://hat-valley.htb/js/.git/logs/ 
thread 'tokio-runtime-worker' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', /build/feroxbuster-quLTbv/feroxbuster-2.7.1/"/build/feroxbuster-quLTbv/feroxbuster-2.7.1/target/cargo"/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.10/src/into_url.rs:70:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: IOT instruction  feroxbuster --no-state -egBE -w  -x  -C 403,404 -u 'http://hat-valley.htb/'
```

Stack backtrace with the `RUST_BACKTRACE=1 RUST_BACKTRACE=full` variables:
```
thread 'tokio-runtime-worker' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', /build/feroxbuster-quLTbv/feroxbuster-2.7.1/"/build/feroxbuster-quLTbv/feroxbuster-2.7.1/target/cargo"/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.10/src/into_url.rs:70:14
stack backtrace:
   0:     0x55b61c079e6f - <unknown>
   1:     0x55b61bda9dfc - <unknown>
   2:     0x55b61c05e704 - <unknown>
   3:     0x55b61c061a1b - <unknown>
   4:     0x55b61c062603 - <unknown>
   5:     0x55b61c07a262 - <unknown>
   6:     0x55b61c07a1d6 - <unknown>
   7:     0x55b61c061ef2 - <unknown>
   8:     0x55b61bd0a742 - <unknown>
   9:     0x55b61bd0ab02 - <unknown>
  10:     0x55b61c00cff1 - <unknown>
  11:     0x55b61be45a26 - <unknown>
  12:     0x55b61be6be0b - <unknown>
  13:     0x55b61be6a356 - <unknown>
  14:     0x55b61be8232c - <unknown>
  15:     0x55b61be80075 - <unknown>
  16:     0x55b61be7afca - <unknown>
  17:     0x55b61c096f39 - <unknown>
  18:     0x55b61c094abf - <unknown>
  19:     0x55b61c08a5f7 - <unknown>
  20:     0x55b61c08a42f - <unknown>
  21:     0x55b61c05fad5 - <unknown>
  22:     0x7f91c488784a - <unknown>
  23:     0x7f91c490b2cc - <unknown>
  24:                0x0 - <unknown>
```

Running the scan again still shows the issue.

Temporary workaround is to reduce recursion depth or straight up disable it with `-n`.

 - feroxbuster version: 2.7.1
 - OS: Kali Linux

**Comment by epi052** [comment]
howdy, and thanks for submitting the report! 

I should be able to check this out tomorrow

**Comment by godylockz** [comment]
@epi052 Hey I was also looking at this machine and noticed that the extract links option is not working for the initial target URL.
I thought it was just because the filtered was not captured `<link hrefs=` but adding that in, did not do the job. Example below:
`<link href="/js/app.js" rel="preload" as="script"><link href="/js/chunk-vendors.js" rel="preload" as="script">`

Add to line 215 in src/extractor/container.rs:
```rust
self.extract_links_by_attr(resp_url, links, html, "link", "href");
```

I was analyzing the code and looks like the robots and directory heuristic are the only ones run on the initial target URL and then dumped into looping with words for the input wordlist. Not sure if its because this was matching the wildcard test. Let me know what you think.

I can open up a new issue for this if more appropriate.

**Comment by epi052** [comment]
i ran this down as far as the panic, which is that urls are getting created with a double quote in the domain 

```
Url {... Domain("\"") ... }
```

For that in particular, I'd lean more toward the javascript being weird than the regex being wrong, but would believe either one is the culprit. The reason I lean toward the javascript is that the regex is what linkfinder uses, and across both tools, it's gotten quite a bit of use, lol.

**Comment by epi052** [comment]
Ok, I finally got back to this and got everything fixed up. The culprit was the html extraction and lack of validation afterward. We assumed that things like `<img src='...'>` returned mostly valid stuff (either a absolute/relative url). The htb machine that was causing exceptions had things like 

```
<img src=\\\"\" + _static_blue_png__WEBPACK_IMPORTED_MODULE_2___default.a + \"\\\" alt=\\\"#\\\" data-v-4c40c86c>
```

causing things to be added where domains were nonsensical 

```
Url {... Domain("\"") ... }
```

The fix was to strip out invalid url characters during extraction and ensure that fully built urls (after extraction completes) still make sense.

Will merge the PR here soon.
